interface TodoItem {
  progress: "TODO" | "DONE";
  title: string;
  level: 1 | 2 | 3;
  priority: "high" | "medium" | "low";
  dueDate: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
  author: string;
}

const todoData: TodoItem[] = [
  {
    progress: "TODO",
    title: "코드 리뷰",
    level: 3,
    priority: "medium",
    dueDate: "Sun",
    author: "최수연",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 1,
    priority: "high",
    dueDate: "Tue",
    author: "김철수",
  },
  {
    progress: "TODO",
    title: "프로젝트 검토",
    level: 1,
    priority: "low",
    dueDate: "Sun",
    author: "최수연",
  },
  {
    progress: "DONE",
    title: "프로젝트 검토",
    level: 2,
    priority: "high",
    dueDate: "Sat",
    author: "최수연",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 2,
    priority: "low",
    dueDate: "Mon",
    author: "이영희",
  },
  {
    progress: "DONE",
    title: "프로젝트 검토",
    level: 3,
    priority: "medium",
    dueDate: "Sat",
    author: "최수연",
  },
  {
    progress: "DONE",
    title: "프로젝트 검토",
    level: 2,
    priority: "high",
    dueDate: "Thu",
    author: "이영희",
  },
  {
    progress: "TODO",
    title: "보고서 작성",
    level: 3,
    priority: "high",
    dueDate: "Wed",
    author: "최수연",
  },
  {
    progress: "DONE",
    title: "보고서 작성",
    level: 3,
    priority: "medium",
    dueDate: "Wed",
    author: "박지민",
  },
  {
    progress: "TODO",
    title: "코드 리뷰",
    level: 1,
    priority: "low",
    dueDate: "Sun",
    author: "최수연",
  },
  {
    progress: "TODO",
    title: "프로젝트 검토",
    level: 3,
    priority: "medium",
    dueDate: "Tue",
    author: "김철수",
  },
  {
    progress: "TODO",
    title: "코드 리뷰",
    level: 2,
    priority: "low",
    dueDate: "Tue",
    author: "박지민",
  },
  {
    progress: "DONE",
    title: "프로젝트 검토",
    level: 3,
    priority: "low",
    dueDate: "Thu",
    author: "김철수",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 1,
    priority: "medium",
    dueDate: "Fri",
    author: "이영희",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 3,
    priority: "high",
    dueDate: "Mon",
    author: "최수연",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 1,
    priority: "high",
    dueDate: "Mon",
    author: "최수연",
  },
  {
    progress: "DONE",
    title: "회의 준비",
    level: 1,
    priority: "low",
    dueDate: "Tue",
    author: "이영희",
  },
  {
    progress: "DONE",
    title: "프로젝트 검토",
    level: 2,
    priority: "medium",
    dueDate: "Sat",
    author: "김철수",
  },
  {
    progress: "DONE",
    title: "보고서 작성",
    level: 3,
    priority: "low",
    dueDate: "Sat",
    author: "박지민",
  },
  {
    progress: "TODO",
    title: "회의 준비",
    level: 3,
    priority: "medium",
    dueDate: "Tue",
    author: "이영희",
  },
];
